# ---------------- #
#   Main Configs   #
# ---------------- #
url: https://lpq29743.github.io/redant
title: Redant Blog
subtitle: "Software is like sex: it's better when it's free."
description: "林佩勤的个人博客"
keywords: 林佩勤, Peiqin Lin, redant, 哈哈大炮
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Peiqin Lin
github_username: lpq29743
location: Guangdong, China
email: lpq29743@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /redant/
    label: 首页

  -
    href: /redant/categories/
    label: 分类

  -
    href: /redant/wiki/
    label: 维基

  -
    href: /redant/about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lpq29743/redant

gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
