# Site Settings
url: https://lpq29743.github.io/redant
title: Redant Blog
subtitle: "Software is like sex: it's better when it's free."
description: "林佩勤的个人博客"
keywords: 林佩勤, Peiqin Lin, redant, 哈哈大炮
timezone: Asia/Shanghai
encoding: "utf-8"
SEOTitle: 林佩勤的个人博客
repository: lpq29743/redant

# Author Settings
author: Peiqin Lin
github_username: lpq29743
location: Guangdong, China
email: lpq29743@gmail.com

# Navigation Settings
navs:
  -
    href: 
    label: 首页
  -
    href: /categories
    label: 分类
  -
    href: /wiki
    label: 维基
  -
    href: /about
    label: 关于

# RSS Settings
RSS: true
subscribe_rss: /feed.xml

# Build Settings
highlighter: rouge
paginate: 10
permalink: pretty
gems: [jekyll-paginate]
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM

